name: examples

on: [push, pull_request]

jobs:
  example_android:
    runs-on: ubuntu-18.04
    strategy:
      type:
        version: [debug, release]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: build
        run: |
          cd example && flutter build apk --${{ matrix.type }}

  example_ios:
    runs-on: macos-latest
    strategy:
      type:
        version: [debug, release]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - name: build
        run: |
          cd example && flutter build ios --${{ matrix.type }} --no-codesign
