name: examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  example_android:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: build
        run: |
          cd example && flutter build apk --debug

  example_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - name: build
        run: |
          cd example && flutter build ios --debug --no-codesign
