name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Test
        run: |
          flutter pub get
          flutter test

  drive_ios:
    strategy:
      matrix:
        device:
          - "iPhone 12 Pro"
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: futureware-tech/simulator-action@v1
        with:
          model: '${{ matrix.device }}'
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      # Run flutter integrate tests
      - name: Run Flutter integration tests
        run: cd example && flutter test integration_test/media_info_test.dart

  drive_android:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: cd example && flutter test integration_test/media_info_test.dart
